### Get all posts
GET http://localhost:8080/generated/posts

### Get post by ID
GET http://localhost:8080/generated/posts/3

### Create a new post
POST http://localhost:8080/generated/posts
Content-Type: application/json

{
  "title": "test title",
  "body": "test body",
  "userId": 1
}

### Update a post
PUT http://localhost:8080/generated/posts/1
Content-Type: application/json

{
  "title": "updated title",
  "body": "updated body",
  "userId": 1
}